spring:
  profiles:
    active: test
  mail:
    username: ${zhaodazi.email.username}
    password: ${zhaodazi.email.password}
    host: ${zhaodazi.email.host}
  datasource:
    druid:
      initial-size: 3
    password: ${zhaodazi.mysql.password}
    url: ${zhaodazi.mysql.url}
    username: ${zhaodazi.mysql.username}
  data:
    redis:
      host: ${zhaodazi.redis.host}
      port: ${zhaodazi.redis.port}


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.lu.zhaodazi
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    org.lu.zhaodazi:
      user.dao: debug
      common.util: debug


